Update configure with acr-1.9.4 (adds --quiet)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.8.1
+# This script was automatically generated by ACR v1.9.4
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -38,6 +38,11 @@ eval "$1_OS=\"$SPLIT_OS\""
 shift
 [ -z "$1" ] && break
 done
+}
+
+QUIET=0
+be_quiet() {
+	QUIET=1
 }
 
 VPATH=`dirname ${0}`
@@ -121,6 +126,7 @@ Defaults for the options are specified in brackets.
 Configuration:
   -h, --help              display this help and exit
   -r, --report            show what libs/programs require to work
+  -q, --quiet             be less verbose
   -V, --version           display version information and exit
 
 Installation directories:
@@ -181,8 +187,22 @@ take_environ() {
 : ${PREFIX:=/usr/local/}
 }
 
+ochof() {
+	[ "$QUIET" = 1 ] && return
+	printf "$*"
+}
+
+ocho() {
+	[ "$QUIET" = 1 ] && return
+	echo "$*"
+}
+
 show_version() {
-echo "r2frida-4.5.0 configuration script done with acr v1.8.1.
+if [ "$QUIET" = 1 ]; then
+	echo "4.5.0"
+	exit 0
+fi
+echo "r2frida-4.5.0 configuration script done with acr v1.9.4.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -202,6 +222,11 @@ fi
 case $flag in
 -h|--help|--hel|--h|--he|-help)
 	show_usage ; ;;
+-qV|-quiet-version|--quiet-version)
+	be_quiet
+	show_version ; ;;
+-q|-quiet|--quiet)
+	be_quiet ; ;;
 -V|-version|--version)
 	show_version ; ;;
 -r|--r|--report)
@@ -277,15 +302,15 @@ ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCD
 
 create_environ
 
-echo "checking build system type... ${BUILD}"
-echo "checking host system type... ${HOST}"
-echo "checking target system type... ${TARGET}"
+ocho "checking build system type... ${BUILD}"
+ocho "checking host system type... ${HOST}"
+ocho "checking target system type... ${TARGET}"
 [ "${CROSSBUILD}" = 1 ] && echo "using crosscompilation mode."
 
 #split_host BUILD HOST TARGET
 [ -n "${prefix}" ] && PREFIX="${prefix}"
-echo "checking for working directories... ${WODIS}"
-echo "using prefix '${PREFIX}'"
+ocho "checking for working directories... ${WODIS}"
+ocho "using prefix '${PREFIX}'"
 ACR_RMFILES=" test.c a.out a.exe test.c test.cxx a.out a.exe"
 
 
@@ -332,7 +357,7 @@ tmp=`${PKGCONFIG} --libs r_core 2>/dev/null`
 if [ $? = 0 ]; then
 echo yes; HAVE_PKGCFG_R_CORE=1;
 R2_LDFLAGS=$tmp; fi; fi
-printf "checking for curl... "
+ochof "checking for curl... "
 if [ -x "${CURL}" ]; then
 	FIND=${CURL}
 else
@@ -347,14 +372,18 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_CURL=1
 	CURL=${FIND}
 else
 	HAVE_CURL=0
 	CURL=curl
-echo no ; fi
-printf "checking for wget... "
+if [ "" = 1 ]; then
+echo "Cannot find curl" >&2
+else
+echo no
+fi ; fi
+ochof "checking for wget... "
 if [ -x "${WGET}" ]; then
 	FIND=${WGET}
 else
@@ -369,14 +398,18 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_WGET=1
 	WGET=${FIND}
 else
 	HAVE_WGET=0
 	WGET=wget
-echo no ; fi
-printf "checking for git... "
+if [ "" = 1 ]; then
+echo "Cannot find wget" >&2
+else
+echo no
+fi ; fi
+ochof "checking for git... "
 if [ -x "${GIT}" ]; then
 	FIND=${GIT}
 else
@@ -391,16 +424,20 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_GIT=1
 	GIT=${FIND}
 else
 	HAVE_GIT=0
 	GIT=git
+if [ "" = 1 ]; then
+echo "Cannot find git" >&2
+else
 echo no
+fi
 	echo "error: This program is required." >&2
 	exit 1 ; fi
-printf "checking for xz... "
+ochof "checking for xz... "
 if [ -x "${XZ}" ]; then
 	FIND=${XZ}
 else
@@ -415,16 +452,20 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_XZ=1
 	XZ=${FIND}
 else
 	HAVE_XZ=0
 	XZ=xz
+if [ "" = 1 ]; then
+echo "Cannot find xz" >&2
+else
 echo no
+fi
 	echo "error: This program is required." >&2
 	exit 1 ; fi
-printf "checking for node... "
+ochof "checking for node... "
 if [ -x "${NODE}" ]; then
 	FIND=${NODE}
 else
@@ -439,16 +480,20 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_NODE=1
 	NODE=${FIND}
 else
 	HAVE_NODE=0
 	NODE=node
+if [ "" = 1 ]; then
+echo "Cannot find node" >&2
+else
 echo no
+fi
 	echo "error: This program is required." >&2
 	exit 1 ; fi
-printf "checking for npm... "
+ochof "checking for npm... "
 if [ -x "${NPM}" ]; then
 	FIND=${NPM}
 else
@@ -463,13 +508,17 @@ else
 	unset IFS
 fi
 if [ -n "${FIND}" ]; then
-	echo ${FIND};
+	ocho ${FIND};
 HAVE_NPM=1
 	NPM=${FIND}
 else
 	HAVE_NPM=0
 	NPM=npm
+if [ "" = 1 ]; then
+echo "Cannot find npm" >&2
+else
 echo no
+fi
 	echo "error: This program is required." >&2
 	exit 1 ; fi
 if [ 11 = "$WANT_CYLANG$HAVE_LANG_CXX" ]; then
@@ -501,7 +550,7 @@ if [ -f "${VPATH}/${A}.acr" ]; then
    exit 1
   fi
  fi
- echo "creating ${SD_TARGET}"
+ ocho "creating ${SD_TARGET}"
 mkdir -p $(echo ${A} | sed -e "s,/`basename ${A}`$,,g")
  cat ${VPATH}/${SD_TARGET}.acr | \
 eval sed -e "s,@VPATH@,${VPATH}/${A},g" ${SEDFLAGS} > ${SD_TARGET}.tmp
@@ -521,10 +570,12 @@ done
 done
 
 do_remove
+if [ "$QUIET" = 0 ]; then
 echo
 echo "Final report:"
-for A in  WITH_CYLANG ; do # REPORT
+for A in  WITH_CYLANG ; do
 eval VAL="\$${A}"
 [ -z "${VAL}" ] && VAL="(null)"
 echo " - ${A} = ${VAL}"
 done
+fi
