Release r2frida 2.2.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,9 +1,10 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.1
+# This script was automatically generated by ACR v1.4
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
 
+[ -z "${AWK}" ] && AWK=awk
 do_remove() {
 if [ "${ACR_RMFILES}" ]; then
   printf "cleaning temporally files... "
@@ -24,7 +25,7 @@ while : ; do
 ENVWORDS="${ENVWORDS} $1_CPU $1_OS"
 STR=`eval "echo ${S}$1"`
 SPLIT_CPU="`echo "$STR" | cut -d - -f 1`"
-SPLIT_OS="`echo "$STR" | awk -F - '{
+SPLIT_OS="`echo "$STR" | $AWK -F - '{
 	if ($2=="unknown"){
 		if (NF<3) { print $2; } else { print $3; }
 	} else {
@@ -40,7 +41,7 @@ done
 }
 
 VPATH=`dirname ${0}`
-if [ "${VPATH}" = "." ]; then 
+if [ "${VPATH}" = "." ]; then
 	WODIS=current
 else
 	if [ "${VPATH}" = "${PWD}" ]; then
@@ -89,7 +90,7 @@ create_environ() {
 : ${DATADIR:="${SPREFIX}/share"}
 : ${INFODIR:="${DATADIR}/info"}
 : ${MANDIR:="${DATADIR}/man"}
-: ${DOCDIR:="${DOCDIR}/man"}
+: ${DOCDIR:="${DATADIR}/doc/radare2"}
 : ${LOCALSTATEDIR:="${SPREFIX}/var"}
 for A in `echo ${PATH} | sed -e 's,:, ,g'` ; do
   [ -e "$A"/ginstall ] && : ${INSTALL:="$A"/ginstall} && break
@@ -102,12 +103,12 @@ done
 : ${INSTALL_PROGRAM_STRIP:=${INSTALL} -m 755 -s}
 : ${INSTALL_MAN:=${INSTALL} -m 444}
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
- PKGNAME='radare2' ; VERSION='1.7.0' ; CONTACT_MAIL="pancake@nowsecure.com" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nowsecure.com>" ;
+ PKGNAME='radare2' ; VERSION='2.2.0' ; CONTACT_MAIL="pancake@nowsecure.com" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nowsecure.com>" ;
 }
-                
+
 show_usage() {
 cat <<EOF2
-'configure' configures radare2-1.7.0 to adapt to many kinds of systems.
+'configure' configures radare2-2.2.0 to adapt to many kinds of systems.
 
 Usage: ./configure [OPTION]... [VAR=VALUE]...
 
@@ -118,28 +119,28 @@ Defaults for the options are specified in brackets.
 
 Configuration:
   -h, --help              display this help and exit
-  -V, --version           display version information and exit
   -r, --report            show what libs/programs require to work
+  -V, --version           display version information and exit
 
 Installation directories:
-  --prefix=PREFIX        install arch-independent files in PREFIX [/usr/local]
   --exec-prefix=EPREFIX  install arch-dependent files in EPREFIX [PREFIX]
+  --prefix=PREFIX        install arch-independent files in PREFIX [/usr/local]
   --sandbox=SPREFIX      sandbox prefix directory: SPREFIX [PREFIX]
 
 Fine tuning of the installation directories:
   --bindir=DIR           user executables [EPREFIX/bin]
-  --sbindir=DIR          system admin executables [EPREFIX/sbin]
-  --libexecdir=DIR       program executables [EPREFIX/libexec]
-  --docdir=DIR           documentation directory [PREFIX/doc]
   --datadir=DIR          read-only architecture-independent data [PREFIX/share]
-  --sysconfdir=DIR       read-only single-machine data [PREFIX/etc]
-  --sharedstatedir=DIR   modifiable architecture-independent data [PREFIX/com]
-  --localstatedir=DIR    modifiable single-machine data [PREFIX/var]
-  --libdir=DIR           object code libraries [EPREFIX/lib]
-  --libpath=DIR          set rpath/libname-path to linker
+  --docdir=DIR           documentation directory [DATADIR/doc/radare2]
   --includedir=DIR       C header files [PREFIX/include]
   --infodir=DIR          info documentation [DATADIR/info]
+  --libexecdir=DIR       program executables [EPREFIX/libexec]
+  --libdir=DIR           object code libraries [EPREFIX/lib]
+  --libpath=DIR          set rpath/libname-path to linker
+  --localstatedir=DIR    modifiable single-machine data [PREFIX/var]
   --mandir=DIR           man documentation [DATADIR/man]
+  --sbindir=DIR          system admin executables [EPREFIX/sbin]
+  --sysconfdir=DIR       read-only single-machine data [PREFIX/etc]
+  --sharedstatedir=DIR   modifiable architecture-independent data [PREFIX/com]
 
 System types:
   --build=BUILD          configure for building on BUILD [guessed]
@@ -149,7 +150,7 @@ EOF2
 
 printf "
 Optional Features:
-  --with-cylang          build with cylang (mjolner) support 
+  --with-cylang          build with cylang (mjolner) support
 "
 printf "
 Some influential environment variables:
@@ -180,7 +181,7 @@ take_environ() {
 }
 
 show_version() {
-echo "radare2-1.7.0 configuration script done with acr v1.1.
+echo "radare2-2.2.0 configuration script done with acr v1.4.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -188,7 +189,7 @@ exit 0
 
 parse_options() {
 flag=`echo $1| cut -d = -f 1`
-value=`echo $1| awk 'BEGIN{FS="=";}{print $2}'`
+value=`echo $1| $AWK 'BEGIN{FS="=";}{print $2}'`
 flag2=`echo $flag|cut -f2- -d -| sed -e 's,-,_,g' -e 's,^_,,g'|tr '[a-z]' '[A-Z]'`
 
 if [ "${TARGET_OS}" = "darwin" ]; then
@@ -204,13 +205,13 @@ case $flag in
 	show_version ; ;;
 -r|--r|--report)
 echo "PKGNAME:   radare2"
-echo "VERSION:   1.7.0"
+echo "VERSION:   2.2.0"
 echo "LANGS:     c c++"
 echo "PKG-CONFIG:  r_core"
 echo "FLAGS:     --with-cylang"
 	exit 0
 	;;
---cache-file) 
+--cache-file)
 	# ignored: acr have no cache
 	;;
 --build)
@@ -254,7 +255,7 @@ echo "FLAGS:     --with-cylang"
 	MANDIR="$value"; ;;
 
 "--with-cylang") WANT_CYLANG="1"; ;;
-*) if [ "$value" ]; then eval "`echo $flag2=$value`" ; 
+*) if [ "$value" ]; then eval "`echo $flag2=$value`" ;
 else echo ; echo "WARNING: Unknown flag '$flag'." >&2 ; echo ; fi ;;
 esac
 }
@@ -286,7 +287,7 @@ echo "checking for working directories... ${WODIS}"
 echo "using prefix '${PREFIX}'"
 ACR_RMFILES=" test.c a.out a.exe test.c test.cxx a.out a.exe"
 
-: 
+
 COMPILER=CC
 printf "checking for c compiler... "
 HAVE_LANG_C=1
@@ -316,17 +317,18 @@ HAVE_LANG_CXX=0
 echo no
  fi
 [ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
+type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find PKGCONFIG ${PKGCONFIG}"
 echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for r_core... '
 tmp=`${PKGCONFIG} --cflags r_core 2>/dev/null`
-if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_R_CORE=0; 
+if [ $? != 0 ]; then echo no ; HAVE_PKGCFG_R_CORE=0;
 echo 'This package is required'
 exit 1
-else 
-R2_CFLAGS=$tmp; 
+else
+R2_CFLAGS=$tmp;
 tmp=`${PKGCONFIG} --libs r_core 2>/dev/null`
-if [ $? = 0 ]; then 
-echo yes; HAVE_PKGCFG_R_CORE=1; 
+if [ $? = 0 ]; then
+echo yes; HAVE_PKGCFG_R_CORE=1;
 R2_LDFLAGS=$tmp; fi; fi
 printf "checking for curl... "
 if [ -x "${CURL}" ]; then
@@ -477,7 +479,7 @@ SEDFLAGS=" -e '"
 COUNT=0
 for A in ${ENVWORDS} ; do
 	[ "${A}" = VPATH ] && continue
-	[ "${A}" = srcdir ] && continue 
+	[ "${A}" = srcdir ] && continue
 	eval "VAR=\$${A}"
 	VAR="`echo ${VAR} | sed -e 's/\,/\\\,/g'`"
 	[ $COUNT = 10 ] && COUNT=0 && SEDFLAGS="${SEDFLAGS}' -e '"
@@ -508,7 +510,7 @@ if [ "$VALUE" = 0 ]; then ## FALSE
  MARK="##${A}##"
 if [ -n "`grep \"${MARK}\" ${SD_TARGET}.tmp`" ]; then
  mv ${SD_TARGET}.tmp ${SD_TARGET}.tmp2
- cat ${SD_TARGET}.tmp2 | MARK=$MARK awk 'BEGIN{a=0;}{if($1==ENVIRON["MARK"]){if(a)a=0;else a=1}else{if(!a)print;}}' > ${SD_TARGET}.tmp
+ cat ${SD_TARGET}.tmp2 | MARK=$MARK $AWK 'BEGIN{a=0;}{if($1==ENVIRON["MARK"]){if(a)a=0;else a=1}else{if(!a)print;}}' > ${SD_TARGET}.tmp
  fi
 fi
 done
