Instruct via acr that r2 is mandatory to build r2frida

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v2.1.1
+# This script was automatically generated by ACR v2.1.2
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -93,8 +93,8 @@ create_environ() {
 : ${SBINDIR:="${PREFIX}/sbin"}
 : ${ETCDIR:="${SPREFIX}/etc"}
 : ${LIBDIR:="${SPREFIX}/lib"}
-: ${PKGCFG_LIBDIR:="\${exec_prefix}/lib"}
-: ${PKGCFG_INCDIR:="\${prefix}/include"}
+: ${PKGCFG_LIBDIR:='${exec_prefix}/lib'}
+: ${PKGCFG_INCDIR:='${prefix}/include'}
 : ${LIBEXECDIR:="${SPREFIX}/libexec"}
 : ${INCLUDEDIR:="${SPREFIX}/include"}
 : ${DATADIR:="${SPREFIX}/share"}
@@ -203,7 +203,7 @@ if [ "$QUIET" = 1 ]; then
 	echo "5.8.8"
 	exit 0
 fi
-echo "r2frida-5.8.8 configuration script done with acr v2.1.1.
+echo "r2frida-5.8.8 configuration script done with acr v2.1.2.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -371,6 +371,7 @@ if [ $? = 0 ]; then
 else
 	R2_VERSION=""
 	echo "not found"
+echo 'required'; exit 1
 fi
 if [ -z "${PKGCONFIG}" ]; then pkg-config --version >/dev/null 2>&1 ; if [ 0 = 0 ]; then PKGCONFIG=pkg-config ; else PKGCONFIG=pkgconf ; fi; fi
 type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find valid PKGCONFIG, pkg-config or pkgconf in PATH"
