Update for the latest ACR-1.9.8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v1.9.4
+# This script was automatically generated by ACR v1.9.8
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -108,12 +108,12 @@ done
 : ${INSTALL_PROGRAM_STRIP:=${INSTALL} -m 755 -s}
 : ${INSTALL_MAN:=${INSTALL} -m 444}
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
- PKGNAME='r2frida' ; VERSION='5.0.1' ; VERSION_MAJOR=5; VERSION_MINOR=0; VERSION_PATCH=1; VERSION_NUMBER=50001; CONTACT_MAIL="pancake@nowsecure.com" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nowsecure.com>" ;
+ PKGNAME='r2frida' ; VERSION='5.0.2' ; VERSION_MAJOR=5; VERSION_MINOR=0; VERSION_PATCH=2; VERSION_NUMBER=50002; CONTACT_MAIL="pancake@nowsecure.com" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nowsecure.com>" ;
 }
 
 show_usage() {
 cat <<EOF2
-'configure' configures r2frida-5.0.1 to adapt to many kinds of systems.
+'configure' configures r2frida-5.0.2 to adapt to many kinds of systems.
 
 Usage: ./configure [OPTION]... [VAR=VALUE]...
 
@@ -125,7 +125,7 @@ Defaults for the options are specified in brackets.
 Configuration:
   -h, --help              display this help and exit
   -r, --report            show what libs/programs require to work
-  -q, --quiet             be less verbose
+  -q, --quiet             be quiet, less verbose (see ./configure -qV)
   -V, --version           display version information and exit
 
 Installation directories:
@@ -163,8 +163,6 @@ Some influential environment variables:
   CPPFLAGS    C/C++ preprocessor flags, e.g. -I<include dir> if you have
               headers in a nonstandard directory <include dir>
   CPP         C preprocessor
-  CXX         C++ compiler command
-  CXXFLAGS    C++ compiler flags
 "
 printf "
 Report bugs to: pancake <pancake@nowsecure.com>"
@@ -176,8 +174,6 @@ take_environ() {
 : ${SH:=/bin/sh}
 : ${CPP:=cpp}
 : ${CC:=gcc}
-: ${CPP:=cpp}
-: ${CXX:=g++}
 : ${PREFIX:=/usr/local/}
 }
 
@@ -193,10 +189,10 @@ ocho() {
 
 show_version() {
 if [ "$QUIET" = 1 ]; then
-	echo "5.0.1"
+	echo "5.0.2"
 	exit 0
 fi
-echo "r2frida-5.0.1 configuration script done with acr v1.9.4.
+echo "r2frida-5.0.2 configuration script done with acr v1.9.8.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -225,8 +221,8 @@ case $flag in
 	show_version ; ;;
 -r|--r|--report)
 echo "PKGNAME:   r2frida"
-echo "VERSION:   5.0.1"
-echo "LANGS:     c c++"
+echo "VERSION:   5.0.2"
+echo "LANGS:     c"
 echo "PKG-CONFIG:  r_core"
 	exit 0
 	;;
@@ -290,7 +286,7 @@ parse_options "$1"
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C CXX CXXFLAGS HAVE_LANG_CXX R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE HAVE_CURL CURL HAVE_WGET WGET HAVE_GIT GIT HAVE_XZ XZ HAVE_NODE NODE HAVE_NPM NPM"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL PKGCONFIG CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C R2_VERSION R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE HAVE_CURL CURL HAVE_WGET WGET HAVE_GIT GIT HAVE_XZ XZ HAVE_NODE NODE HAVE_NPM NPM"
 
 create_environ
 
@@ -303,11 +299,37 @@ ocho "checking target system type... ${TARGET}"
 [ -n "${prefix}" ] && PREFIX="${prefix}"
 ocho "checking for working directories... ${WODIS}"
 ocho "using prefix '${PREFIX}'"
-ACR_RMFILES=" test.c a.out a.exe test.c test.cxx a.out a.exe"
+ACR_RMFILES=" test.c a.out a.exe"
 
-
+ochof "checking for pkg-config... "
+if [ -n "$PKGCONFIG" ]; then
+	if [ -x "$PKGCONFIG" ]; then
+		_HAVE_PKGCONFIG="${PKGCONFIG}"
+	else
+		ocho "PKGCONFIG env is not executable"
+		PKGCONFIG=""
+	fi
+else
+	IFS=:
+	for A in ${PATH} ; do
+		if [ -x "${A}/pkg-config" ]; then
+			PKGCONFIG="${A}/pkg-config"
+		elif [ -x "${A}/pkgconf" ]; then
+			PKGCONFIG="${A}/pkgconf"
+		else
+			continue
+		fi
+		break
+	done
+	unset IFS
+fi
+if [ -n "${PKGCONFIG}" ]; then
+	ocho ${PKGCONFIG}
+else
+	echo "Cannot find pkg-config or pkgconf in PATH" >&2
+	exit 1 ocho no; fi
 COMPILER=CC
-printf "checking for c compiler... "
+ochof "checking for c compiler... "
 HAVE_LANG_C=1
 if [ "${CROSSBUILD}" = 1 ]; then
  (command -v ${HOST}-${CC} >/dev/null 2>&1)
@@ -320,22 +342,16 @@ if [ $? = 0 ]; then echo ${CC}; else
 do_remove
 echo "ERROR: ${CC} cannot create executables" >&2 ;
 exit 1 ; fi
-COMPILER=CXX
-HAVE_LANG_CXX=1
-printf "checking for c++ compiler... "
-if [ "${CROSSBUILD}" = 1 ]; then
-(command -v ${HOST}-${CXX} 2>&1 >/dev/null)
-if [ "$?" = 0 ]; then CXX="${HOST}-${CXX}"; fi
+printf "checking exec r2 -v... "
+R2_VERSION="`r2 -v 2>/dev/null`"
+if [ $? = 0 ]; then
+	echo "ok"
+else
+	R2_VERSION=""
+	echo "not found"
 fi
-echo "#include <iostream>" > test.cxx
-echo "int main(){ std::cout << 1; return 0;}" >> test.cxx
-(exec ${CXX} ${CXXFLAGS} ${LDFLAGS} test.cxx -lstdc++ >/dev/null 2>&1)
-if [ $? = 0 ]; then echo ${CXX}; else
-HAVE_LANG_CXX=0
-echo no
- fi
-[ -z "${PKGCONFIG}" ] && PKGCONFIG=pkg-config
-type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find PKGCONFIG ${PKGCONFIG}"
+if [ -z "${PKGCONFIG}" ]; then pkg-config --version >/dev/null 2>&1 ; if [ 0 = 0 ]; then PKGCONFIG=pkg-config ; else PKGCONFIG=pkgconf ; fi; fi
+type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find valid PKGCONFIG, pkg-config or pkgconf in PATH"
 echo 'Using PKGCONFIG: '${PKGCONFIG}
 printf 'checking pkg-config flags for r_core... '
 tmp=`${PKGCONFIG} --cflags r_core 2>/dev/null`
@@ -538,7 +554,7 @@ if [ -f "${VPATH}/${A}.acr" ]; then
   fi
  fi
  ocho "creating ${SD_TARGET}"
-mkdir -p $(echo ${A} | sed -e "s,/`basename ${A}`$,,g")
+[ "${VPATH}" != '.' ] &&  mkdir -p $(echo ${A} | sed -e "s,/`basename ${A}`$,,g")
  cat ${VPATH}/${SD_TARGET}.acr | \
 eval sed -e "s,@VPATH@,${VPATH}/${A},g" ${SEDFLAGS} > ${SD_TARGET}.tmp
 
@@ -557,3 +573,12 @@ done
 done
 
 do_remove
+if [ "$QUIET" = 0 ]; then
+echo
+echo "Final report:"
+for A in  R2_VERSION ; do
+eval VAL="\$${A}"
+[ -z "${VAL}" ] && VAL="(null)"
+echo " - ${A} = ${VAL}"
+done
+fi
