Add --with-precompiled-agent configure flag

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -18,6 +18,7 @@ control_c() {
   exit 1
 }
 trap control_c 2
+PRECOMPILED_AGENT=0
 split_host() {
 S="$"
 while : ; do
@@ -109,12 +110,12 @@ done
 : ${INSTALL_PROGRAM_STRIP:=${INSTALL} -m 755 -s}
 : ${INSTALL_MAN:=${INSTALL} -m 444}
 : ${INSTALL_LIB:=${INSTALL} -m 755 -c}
- PKGNAME='r2frida' ; VERSION='5.5.0' ; VERSION_MAJOR=5; VERSION_MINOR=5; VERSION_PATCH=0; VERSION_NUMBER=50500; CONTACT_MAIL="pancake@nowsecure.com" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nowsecure.com>" ;
+ PKGNAME='r2frida' ; VERSION='5.5.4' ; VERSION_MAJOR=5; VERSION_MINOR=5; VERSION_PATCH=4; VERSION_NUMBER=50504; CONTACT_MAIL="pancake@nowsecure.com" ; CONTACT_NAME="pancake" ; CONTACT="pancake <pancake@nowsecure.com>" ;
 }
 
 show_usage() {
 cat <<EOF2
-'configure' configures r2frida-5.5.0 to adapt to many kinds of systems.
+'configure' configures r2frida-5.5.4 to adapt to many kinds of systems.
 
 Usage: ./configure [OPTION]... [VAR=VALUE]...
 
@@ -157,6 +158,11 @@ System types:
 EOF2
 
 printf "
+Optional Features:
+  --with-precompiled-agent
+                          do not require node/npm
+"
+printf "
 Some influential environment variables:
   CC          C compiler command
   CFLAGS      C compiler flags
@@ -191,10 +197,10 @@ ocho() {
 
 show_version() {
 if [ "$QUIET" = 1 ]; then
-	echo "5.5.0"
+	echo "5.5.4"
 	exit 0
 fi
-echo "r2frida-5.5.0 configuration script done with acr v1.9.8.
+echo "r2frida-5.5.4 configuration script done with acr v1.9.8.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -223,9 +229,10 @@ case $flag in
 	show_version ; ;;
 -r|--r|--report)
 echo "PKGNAME:   r2frida"
-echo "VERSION:   5.5.0"
+echo "VERSION:   5.5.4"
 echo "LANGS:     c"
 echo "PKG-CONFIG:  r_core"
+echo "FLAGS:     --with-precompiled-agent"
 	exit 0
 	;;
 --cache-file)
@@ -275,6 +282,7 @@ echo "PKG-CONFIG:  r_core"
 --mandir)
 	MANDIR="$value"; ;;
 
+"--with-precompiled-agent") PRECOMPILED_AGENT="1"; ;;
 *) if [ "$value" ]; then eval "`echo $flag2=$value`" ;
 else echo ; echo "WARNING: Unknown flag '$flag'." >&2 ; echo ; fi ;;
 esac
@@ -292,7 +300,7 @@ parse_options "$1"
 shift
 done
 
-ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR ETCDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL PKGCONFIG CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C R2_VERSION R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE HAVE_CURL CURL HAVE_WGET WGET HAVE_GIT GIT HAVE_XZ XZ HAVE_NODE NODE HAVE_NPM NPM"
+ENVWORDS="MANDIR INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR ETCDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL PKGCONFIG CC CFLAGS CPPFLAGS LDFLAGS HAVE_LANG_C R2_VERSION PRECOMPILED_AGENT HAVE_NODE NODE HAVE_NPM NPM R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE HAVE_CURL CURL HAVE_WGET WGET HAVE_GIT GIT HAVE_XZ XZ"
 
 create_environ
 
@@ -333,7 +341,7 @@ if [ -n "${PKGCONFIG}" ]; then
 	ocho ${PKGCONFIG}
 else
 	echo "Cannot find pkg-config or pkgconf in PATH" >&2
-	exit 1 ocho no; fi
+	exit 1 ; ocho no; fi
 COMPILER=CC
 ochof "checking for c compiler... "
 HAVE_LANG_C=1
@@ -356,6 +364,63 @@ else
 	R2_VERSION=""
 	echo "not found"
 fi
+if [ "$PRECOMPILED_AGENT" = "0" ]; then
+ochof "checking for node... "
+if [ -x "${NODE}" ]; then
+	FIND=${NODE}
+else
+	FIND=""
+	IFS=:
+	for A in ${PATH} ; do
+		if [ -x "${A}/node" ]; then
+			FIND="${A}/node"
+			break;
+		fi
+	done
+	unset IFS
+fi
+if [ -n "${FIND}" ]; then
+	ocho ${FIND};
+HAVE_NODE=1
+	NODE=${FIND}
+else
+	HAVE_NODE=0
+	NODE=node
+if [ "" = 1 ]; then
+echo "Cannot find node" >&2
+else
+echo no
+fi
+	echo "error: This program is required." >&2
+	exit 1 ; fi
+ochof "checking for npm... "
+if [ -x "${NPM}" ]; then
+	FIND=${NPM}
+else
+	FIND=""
+	IFS=:
+	for A in ${PATH} ; do
+		if [ -x "${A}/npm" ]; then
+			FIND="${A}/npm"
+			break;
+		fi
+	done
+	unset IFS
+fi
+if [ -n "${FIND}" ]; then
+	ocho ${FIND};
+HAVE_NPM=1
+	NPM=${FIND}
+else
+	HAVE_NPM=0
+	NPM=npm
+if [ "" = 1 ]; then
+echo "Cannot find npm" >&2
+else
+echo no
+fi
+	echo "error: This program is required." >&2
+	exit 1 ; fi; fi
 if [ -z "${PKGCONFIG}" ]; then pkg-config --version >/dev/null 2>&1 ; if [ 0 = 0 ]; then PKGCONFIG=pkg-config ; else PKGCONFIG=pkgconf ; fi; fi
 type ${PKGCONFIG} > /dev/null 2>&1 || echo "ERROR: Cannot find valid PKGCONFIG, pkg-config or pkgconf in PATH"
 echo 'Using PKGCONFIG: '${PKGCONFIG}
@@ -474,62 +539,6 @@ else
 	XZ=xz
 if [ "" = 1 ]; then
 echo "Cannot find xz" >&2
-else
-echo no
-fi
-	echo "error: This program is required." >&2
-	exit 1 ; fi
-ochof "checking for node... "
-if [ -x "${NODE}" ]; then
-	FIND=${NODE}
-else
-	FIND=""
-	IFS=:
-	for A in ${PATH} ; do
-		if [ -x "${A}/node" ]; then
-			FIND="${A}/node"
-			break;
-		fi
-	done
-	unset IFS
-fi
-if [ -n "${FIND}" ]; then
-	ocho ${FIND};
-HAVE_NODE=1
-	NODE=${FIND}
-else
-	HAVE_NODE=0
-	NODE=node
-if [ "" = 1 ]; then
-echo "Cannot find node" >&2
-else
-echo no
-fi
-	echo "error: This program is required." >&2
-	exit 1 ; fi
-ochof "checking for npm... "
-if [ -x "${NPM}" ]; then
-	FIND=${NPM}
-else
-	FIND=""
-	IFS=:
-	for A in ${PATH} ; do
-		if [ -x "${A}/npm" ]; then
-			FIND="${A}/npm"
-			break;
-		fi
-	done
-	unset IFS
-fi
-if [ -n "${FIND}" ]; then
-	ocho ${FIND};
-HAVE_NPM=1
-	NPM=${FIND}
-else
-	HAVE_NPM=0
-	NPM=npm
-if [ "" = 1 ]; then
-echo "Cannot find npm" >&2
 else
 echo no
 fi
