Early error at configure stage if curl and wget are not available

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v2.0.0
+# This script was automatically generated by ACR v1.9.9
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -200,7 +200,7 @@ if [ "$QUIET" = 1 ]; then
 	echo "5.7.2"
 	exit 0
 fi
-echo "r2frida-5.7.2 configuration script done with acr v2.0.0.
+echo "r2frida-5.7.2 configuration script done with acr v1.9.9.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -314,6 +314,7 @@ ocho "checking target system type... ${TARGET}"
 ocho "checking for working directories... ${WODIS}"
 ocho "using prefix '${PREFIX}'"
 ACR_RMFILES=" test.c a.out a.exe"
+
 
 ochof "checking for pkg-config... "
 if [ -n "$PKGCONFIG" ]; then
@@ -545,6 +546,9 @@ echo no
 fi
 	echo "error: This program is required." >&2
 	exit 1 ; fi
+if [ "$HAVE_WGET" = "0" ]; then
+if [ "$HAVE_CURL" = "0" ]; then
+case "$undefined_variable" in 0|"") echo ; echo "ERROR: You need curl or wget to download the Frida SDK" >&2 ; echo ; exit 1 ;; esac; fi; fi
 SEDFLAGS=" -e '"
 COUNT=0
 for A in ${ENVWORDS} ; do
@@ -594,7 +598,7 @@ echo
 echo "Final report:"
 for A in  R2_VERSION ; do
 eval VAL="\$${A}"
-[ -z "${VAL}" ] && VAL="\"\""
+[ -z "${VAL}" ] && VAL="(null)"
 echo " - ${A} = ${VAL}"
 done
 fi
